/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
/* const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  
}
*/

//module.exports = sidebars;

module.exports = {
  StartSidebar: [
    {
      type: 'autogenerated',
      dirName: 'quick start', // Generate sidebar slice from docs/quick start
    },
  ],
  DevSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Build on Morphism', // Generate sidebar slice from docs/Build on Morphism
    },
  ],
  HowSidebar: [
    {
      type: 'autogenerated',
      dirName: 'How Morphism Works', // Generate sidebar slice from docs/How Morphism Works
    }
  ],
};

